{% set name = "unicaps" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/unicaps-{{ version }}.tar.gz
  sha256: 1dfe15810132b1236c39dc994ee571d30a4772fbfaf4f4adeae4ba6b5f056548

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - httpx >=0.22.0
    - enforce-typing >=1.0.0

test:
  imports:
    - unicaps
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sergey-scat/unicaps
  summary: Universal CAPTCHA Solver for humans
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
