{% set name = "unicaps" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/unicaps-{{ version }}.tar.gz
  sha256: 2a83a2a6be03634cb83fedf1e2227bd4ad7f13a2852f3fe42ef67149ee4e785b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - httpx >=0.22.0
    - enforce-typing >=1.0.0

test:
  imports:
    - unicaps
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sergey-scat/unicaps
  summary: Universal CAPTCHA Solver for humans
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
